### ISSUE TITLE
Can't install game if the repo's path contain diacritics

### ISSUE THREAD

**Issue by Kekun** [hadess/flatpak-games#10]
I clones the repo in `~/Développement/flatpak-games` and each step worked up to the installation one:

```
$ flatpak --user install game-repo com.gog.Lovers_In_A_Dangerous_Spacetime


error: While pulling app/com.gog.Lovers_In_A_Dangerous_Spacetime/x86_64/master from remote game-repo: /home/kekun/D%C3%A9veloppement/flatpak-games/repo: openat: Aucun fichier ou dossier de ce type
```

Diacritics don't seem to be well supported at some point.

P.S.: the original game file's path didn't contain any diacritics.

P.P.S.: Or maybe the problem is that `openat` haven't been  found...

**Comment by hadess** [comment]
Can you file the bug against flatpak instead? This isn't a flatpak-games bug.
